### ISSUE TITLE
I've gone through tutorials and forums and still don't understand how to select the truncLen and trim parameters in dada2

### ISSUE THREAD

**Issue by milenapi** [qiime2/q2-dada2#114]
Have you had a chance to check out the docs?
https://docs.qiime2.org
There are many tutorials, walkthroughs, and guides available.

If you still need help, please visit:
https://forum.qiime2.org/c/user-support

Help requests filed here will not be answered.

**Comment by thermokarst** [comment]
Hi @milenapi - I don't see a post from you over on the [QIIME 2 Forum](https://forum.qiiime2.org) --- let's start there. Thanks!
