### ISSUE TITLE
Add ability to join paired reads

### ISSUE THREAD

**Issue by johnchase** [qiime2/q2-dada2#12]
Similar to running dada2 in R it would be nice to have the ability to join paired reads with the q2 plugin

**Comment by benjjneb** [comment]
Is there currently a QIIME object for paired fastq files (or lists of paired fastq files)?

**Comment by johnchase** [comment]
I don't believe that there is. @ebolyen can you confirm?

**Comment by ebolyen** [comment]
There is if I understand the question correctly: `SampleData[PairedEndSequencesWithQuality]` which uses `SingleLanePerSamplePairedEndFastqDirFmt` as its backing directory format.

**Comment by benjjneb** [comment]
If that exists already, then adding a paired end workflow should be straightforward.

Is there documentation of `SampleData[PairedEndSequencesWithQuality]` objects? For example, can it be assumed there are always forward and reverse files for each sample?

**Comment by ebolyen** [comment]
No real documentation, and we can't yet enforce that there *exists* a forward and reverse for each sample, but I believe it is our goal to be able to validate that property. That particular directory format does contain a manifest file which maps the sample id to the filepath and direction.

[relevant lines for format](https://github.com/qiime2/q2-types/blob/master/q2_types/per_sample_sequences/_format.py#L51-L76)
[manifest definition](https://github.com/qiime2/q2-types/blob/master/q2_types/per_sample_sequences/_format.py#L51-L76)
[q2-demux which manipulates these](https://github.com/qiime2/q2-demux)

These parts of the API (multi-file directory formats) are still very rough around the edges, but we're thinking about ways to make it easier.

**Comment by benjjneb** [comment]
Added in a1857e54ef0599e956c2f73bed1b0bc6851ac946 and b66432da308a924a26f315a517c934b4a335af2f

Assumes dada2 1.2+
