### ISSUE TITLE
Setting "allowOneOf" and "maxMismatch" parameters in q2/dada2 plugin

### ISSUE THREAD

**Issue by francis29029** [qiime2/q2-dada2#126]
Hello,

We were used to work with dada2 1.10 and now we want to move to q2 (2019.10) using the DADA2 plugin embedded in q2.

By reading carefully? the documentation of the dada2 plugin (https://docs.qiime2.org/2019.10/plugins/available/dada2/denoise-paired/) we did not find how to adjust the following parameters :

-	allowOneOff of the DADA2 removeBimeraDenovo method (following this discussion: https://github.com/benjjneb/dada2/issues/610)
-	maxMismatch in the DADA2 mergePairs method (we prefer this over having a fixed quality score / sequence length cutoff)

Is there any way to edit these parameters in q2-dada2 ?

Thanks a lot

Francis

**Comment by nbokulich** [comment]
Hi @francis29029 ,
Please see https://forum.qiime2.org/ for posting user support questions. Thank you!
