### ISSUE TITLE
Plugin installation

### ISSUE THREAD

**Issue by benjjneb** [qiime2/q2-dada2#13]
Currently the plugin is installing the dada2 R package via bioconda. Is there any reason not to continue with bioconda install going forward?

Right now this relies on a bioconda recipe submitted by @zachcp, and installs the Bioconductor release version (1.0.3). If bioconda is the long-term installation plan, it is probably best to create a plugin-specific recipe.

I think the time to do this would be with the next release of Bioconductor and the dada2 package, which will be in mid October.

@zachcp Any input? Are you interested in helping with a QIIME2-specific bioconda build?

**Comment by zachcp** [comment]
Hi @benjjneb,

I've been a bit busy and out of the dada2 loop for a bit. What is a plugin installation? 

As for bioconda, they have changed the build system a bit (CentOS5->CentOS6) to be compatible with Conda-Forge and to be able to use newer C-compilers.  So it was in a state of flux for a bit but should have settled down by now. The main problem I had when upgrading to dada2 >= 1.1 was the addition of the RcppParallel dependency. I got that to build (should be available in bioconda - althgouh it should also be bumped for the new build system.) but then was having some issues getting dada2 to build with it. That would take a bit of tinkering with the `conda` build parameters but then it should be very smooth.  

In general if you want to use dada2 as part of a larger non-R workflow then conda/bioconda is your friend. I can try again (maybe this weekend?) to build dada2 on the new build system and am happy to work with anyone else trying to get it done.

zach cp

**Comment by zachcp** [comment]
I got this via email and just realized this is not the main dada2 repo. Make dada2 accessible via qiime. great idea. I can take another stab at upgrading dada2 to use RcppParallel.

**Comment by benjjneb** [comment]
Thanks for taking a look @zachcp 

We do want to migrate the plugin to the next release of dada2 (later this month) which will use RcppParallel, so that's important to figure out.

**Comment by zachcp** [comment]
Updated r-rcppparallel  and dada2 on bioconda but had to disable builds on osx to do so because they were timing out probably due to a backlog of R packages needing to be built for R 3.3.  I can fix this down the line.

I also haven't done any testing beyond the simple "this package loads test".  Note to self: learn to trigger the package's tests post-build

The binaries should be available shortly and then I can kick the tires.

**Comment by benjjneb** [comment]
Wanted to check in on the status of Bioconda OSX builds with RcppParallel?

The new Bioconductor dada2 release will be later this week (with parallel functionality) and we will want to transition the plugin to it as soon as it is working through Bioconda.

**Comment by zachcp** [comment]
I haven't moved on this. I will try to build it today and let you know one way or the other.

**Comment by zachcp** [comment]
looks like theres still issues in bioconda for building packages on OSX (aee https://github.com/bioconda/bioconda-recipes/issues/2404 https://github.com/bioconda/bioconda-recipes/pull/2595) that is exacerbated by the R_3.2->R_3.3  change over.  I've tried to build dada2 but the base bioconductor packages need to be updated first.  The core bioconda team is actively working on this issue. Ill look again tomorrow to check on progress.

zcp

**Comment by gregcaporaso** [comment]
Thanks for working on this @benjjneb and @zachcp, please let me know if there is anything I can do to help. We're planning to do a new release of this plugin (0.0.6) on 2 Nov in preparation for our Phoenix workshop, so we'd need this a few days ahead of time for testing. We're really motivated to get this updated so our users have access to multi-threaded mode (top priority) and paired end data processing (second priority).

**Comment by benjjneb** [comment]
Agreed that getting the 1.2 release available via bioconda is now the top priority, as dependence on the current 1.0.3 version blocks adding multithreading. It would also be better to move to 1.2 prior to implementing the paired-end workflow.

I also want to recognize that @zachcp has done all the work here, as I am not a bioconda nor a python user. I'm motivated to help if I can though. It does seem that there are currently upstream OSX problems from the issues @zachcp referenced though.

**Comment by zachcp** [comment]
@gregcaporaso @benjjneb  I will give a go to try to build some of the dependencies that aren't yet built for dada2.   However, the osx build process is rather slow and the double whammy of 3.2->3.3 and CENTOS5->CENTOS6 has exacerbated the problem. There is currently a bit of build-spaghetti that is being worked through by the core team. 

If you have some experience with conda and the urge to scratch you can try to build any of the dada2  dependencies for OSX (the current offenders seem to be a biobase/biostrings 3.2/3.3 clash).  But I would suggest having a backup plan for your workshop.

For context:
https://github.com/bioconda/bioconda-recipes/issues/2404
https://github.com/bioconda/bioconda-recipes/pull/2644

**Comment by benjjneb** [comment]
Any news on this? This blocks some important functionality.

**Comment by gregcaporaso** [comment]
Not yet, unfortunately. Last I checked (a couple of weeks ago) a few of the dependencies were still not available. We have a meeting scheduled in my group on Jan 9 at noon mountain time to figure this out. We really need the functionality that you mention is blocked (parallel support, paired end support) for our next release. Would you be available to join that meeting @benjjneb?

**Comment by zachcp** [comment]
No progress on my end.  I have just tried updating bioconda's `r-rcppparrallel` package and am running into some compilation errors on osx.  But if we can get `r-rcppparallel`  to work then I think thats the last remaining piece for successfully building dada 1.2

**Comment by benjjneb** [comment]
@gregcaporaso I am probably* available, and would like to skype or listen in if I am.

* It depends on when our moving company delivers our stuff. Could be Jan 6 or Jan 9, and we won't know which until a couple days before.

**Comment by gregcaporaso** [comment]
Ok, great. @benjjneb, @zachcp I'll follow up with you shortly with call-in details. If you can make it that would be fantastic, and no worries if not.

**Comment by benjjneb** [comment]
I am available Jan 9 at noon MST.

**Comment by zachcp** [comment]
I can't make the meeting on Monday but heres the latest with getting RcppParallel to compile on OSX within conda:

https://github.com/bioconda/bioconda-recipes/issues/3340
https://github.com/RcppCore/RcppParallel/issues/40#issuecomment-270770718

looks like issues linking to the TBB libraries used by RcppParallel for threading.

**Comment by gregcaporaso** [comment]
Great, thanks @benjjneb and @zachcp. @benjjneb, I'll get in touch by email with call-in details.

**Comment by zachcp** [comment]
I got rcpp-parallel working https://github.com/bioconda/bioconda-recipes/pull/3347 so I think updating dada2 should now be straightforward.

**Comment by gregcaporaso** [comment]
That's great news @zachcp! Are you planning to update the dada2 conda package, or would you prefer someone else do that? We have a QIIME 2 release coming up in Feb, and are hoping to starting our final testing in late Jan. We really want to use the latest version of DADA2 for this so we can get access to the parallel computing functionality and the paired end read processing.

**Comment by zachcp** [comment]
perhaps I spoke too soon....

I'm now 'm running into a C++ compilation issue for dada2. https://github.com/bioconda/bioconda-recipes/issues/3391#issuecomment-271012178

if you have some experience with the conda build system on OSX, by all means jump in. The r-package dependencies are all up to date so its just a matter of getting the C++ to build correctly. I thought that rcppparallel would be the last of it but I guess not.

**Comment by jairideout** [comment]
Thanks for all your work on this @zachcp! I'll be able to devote some time to work on this (discussed this on a call yesterday with @gregcaporaso, @benjjneb, @thermokarst).

**Comment by zachcp** [comment]
thanks @jairideout .  happy to have you on board. I would check the last thread I linked to as it appears that bioconda is about to move their `r` packages to the conda-forge channel.  It seems that conda-forge is emerging as the consensus community packaging platform so this should results in stability down the line, however, it does mean that you may have to fight the incompatible-compiler problem in the short term.

As an alternative for users of qiime-dada2, it might be worth considering using conda for all python and binary files, while using the perfectly good bioconductor installation for R/dada2. Not quite 1-click, but reliable.  My 2 cents.

**Comment by jairideout** [comment]
Thanks for suggesting the bioconductor installer @zachcp, that sounds easier and more stable at this point while the conda R packages are being updated and shuffled around. We're testing out conda R + bioconductor dada2 installation on a variety of systems and it's been pretty straightforward so far. For the upcoming release I think we'll go this route, and we can revisit for future releases if there's an updated dada2 conda package available.

Thanks again for all your help with this! Are you interested in continuing to work on updating the conda dada2 package once the `r`/`bioconda`/`conda-forge` R packages are more stable?

**Comment by zachcp** [comment]
im happy to keep my eyes open RE: the more to conda-forge and rebuild dada2 once`r` is ported over. although I'm not using dada2 much right now i think its a great tool to have in the conda ecosystem. and am happy build it.  So if you are satisfied with using bioconductor for now, lets hold off until the conda-forge port is complete.  You can ping me down the line if it comes up again.

**Comment by jairideout** [comment]
Sounds good @zachcp, thanks for your help! We're going to use Bioconductor for now and will test out the newer version of dada2 when it's available via conda (I submitted a PR that updates the qiime2 install instructions to use Bioconductor here if you're interested: https://github.com/qiime2/docs/pull/62).

I created a [new issue](https://github.com/qiime2/q2-dada2/issues/33) to track progress on the dada2 bioconda package and will close this one. Please let us know if there's anything we can help with / test, and thanks again for your help!
