### ISSUE TITLE
Update to latest DADA2 for R 4.0 support

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-dada2#133]
**Addition Description**
DADA2 1.16 is available on bioconda which supports R 4.0, and our stale R version is preventing the development of some other plugins.

Just need to verify that the behavior looks reasonable. Tests might break, but usually the changes aren't particularly dramatic.
I think the best approach would be to update the dependency, and then make any API changes after the fact if there are features we would like as well.

**Comment by thermokarst** [comment]
We skipped DADA2 1.16 and went straight to 1.18 (1.18 was released on bioconda after this issue was first opened).
