### ISSUE TITLE
Importing DADA2 R rep. sequences into QIIME2

### ISSUE THREAD

**Issue by dixi06** [qiime2/q2-dada2#159]
I am trying to import dada2R files (rep seq) to QIIME2 for taxonomic classification. I need help with the steps mentioned below.

I tried to extract sequences using dada2:: getSequences(seqtab.nochim) and then saving the file with writeFasta(seqtab.nochime, "rep-seq.fasta")

When I tried to import it in QIIME2 it gives me an error like this
There was a problem importing rep-seq.fasta:

rep-seq.fasta is not a(n) DNAFASTAFormat file:

Description on line 1 is missing an ID.

I tried other ways to convert the data frame into fasta as well but it is not recognizing the file.

**Comment by ebolyen** [comment]
Hi @dixi06, sorry for missing this, could you repost this to the [QIIME 2 forum](https://forum.qiime2.org) you'll receive better support there :)
