### ISSUE TITLE
Add warning when pooling method and chimera detection method are misaligned

### ISSUE THREAD

**Issue by benjjneb** [qiime2/q2-dada2#165]
**Improvement Description**
Provide a warning to the user when `--p-pooling-method` and `--p-chimera-method` are misaligned. In particular, `--p-chimera-method pooled` should only be used when `--p-pooling-method pooled`, otherwise the correctly aligned chimera removal method is `--p-chimera-method concensus`.

**Current Behavior**
No check is made.

**Proposed Behavior**
Warn the user when the pooling method and chimera method are misaligned.

**References**
1. https://github.com/benjjneb/dada2/issues/1942

**Comment by lizgehret** [comment]
Hey @benjjneb, thanks for bringing this up! I think more realistically this should be an error (vs. a warning) - we should be able to do this with a TypeMap. I'll get this added to our upcoming release board and we'll work on this for 2024.10!

**Comment by colinvwood** [comment]
The qiime2 wrapper only accepts `independent` or `pseudo` to the `--p-pooling-method` parameter, so should the `pooled` option to the `--p-chimera-method` parameter simply be removed?

**Comment by benjjneb** [comment]
That's a good point. Yes, probably should be removed, or at least made redundant (for now) by only allowing the one valid option.

**Comment by colinvwood** [comment]
Closed by #171
