### ISSUE TITLE
'... reads from 1 samples will be used' message

### ISSUE THREAD

**Issue by colinbrislawn** [qiime2/q2-dada2#170]
**Improvement Description**
Throw an error when a single sample is passed to DADA2, with an optional flag to bypass this check.

**Current Behavior**
DADA2 will happily process any number of samples.
I like this flexibility, but it seems to confuse non-expert users.

**Proposed Behavior**
Instead of the warning / log saying

`... reads from 1 samples will be used`

I suggest that we raise an error and exit:

`Only one sample has been provided! This may be a mistake. If this is intended, add --p-one-sample and rerun`

EDIT: ⚠️ This next part is not quite right! See comments below
~~This has only happened [30 times](https://forum.qiime2.org/search?q=%22reads%20from%201%20samples%20will%20be%20used) over the last 5 years. But it does keep happening!~~

**Comment by ebolyen** [comment]
Should we actually fail in our demux actions if there's only one sample? Presumably that implies that the demux failed almost by definition (I'm assuming this is the primary source of the data with 1 sample vs importing).

**Comment by colinbrislawn** [comment]
I just spoke with Evan on the forums and learned that 'reads from 1 samples will be used' can still appear when many samples are provided. This means it's not strong evidence for 1 sample being provided after all!

I'll close this issue!

(I still like the idea or throwing an error if demultiplexing returns a single sample.)
