### ISSUE TITLE
Rplots.pdf generated in working directory by plot-qualities

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-dada2#26]
We observed this on the workshop cluster (linux) but I don't see this locally.

**Comment by thermokarst** [comment]
http://stackoverflow.com/questions/6535927/how-do-i-prevent-rplots-pdf-from-being-generated

**Comment by benjjneb** [comment]
Closing since this function is being deprecated for most users in favor of the new interactive quality plot.
