### ISSUE TITLE
Learn error rates from a subset of the data

### ISSUE THREAD

**Issue by benjjneb** [qiime2/q2-dada2#31]
Parameter learning is the most computationally part of the "tutorial" workflow currently implemented. It is much faster, and achieves essentially the same result, to learn the error rates from a subset of the data for larger datasets. This can substantially speed computation times for large datasets (2x-7x faster).

Workflow should add an argument, perhaps `--nreads-learn` with a default of perhaps 1-million, specifying the minimum number of reads used to learn the error rates. Those error rates will then be used to process the entire dataset.

This approach follows that in the DADA2 "big data" workflow: http://benjjneb.github.io/dada2/bigdata.html

**Comment by gregcaporaso** [comment]
This sounds like it would be really helpful. Think we could get this in with the for the next release?

**Comment by benjjneb** [comment]
Yes.

**Comment by benjjneb** [comment]
Added in 685ddae848e46090aea61809373e7c86757f0676 and b66432da308a924a26f315a517c934b4a335af2f

Assumes dada2 1.2+
