### ISSUE TITLE
test latest dada2 bioconda package when available

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-dada2#33]
Currently we are using Bioconductor to install the latest version of dada2 (1.2.1). There is work being done to package this release via bioconda; see https://github.com/qiime2/q2-dada2/issues/13 for previous discussion. When the package is available we'll want to test it with q2-dada2 and update the qiime2 install docs.

cc: @zachcp

**Comment by benjjneb** [comment]
Can this be closed? Seems like bioconda install is now working.

**Comment by ebolyen** [comment]
Good catch!
