### ISSUE TITLE
can `trim-left` and `trunc-len` be made optional and default to no trimming/truncation?

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-dada2#43]
related to #16

**Comment by benjjneb** [comment]
Making `trim-left` optional with a default of 0 would be appropriate right now.

Making `trunc-len` optional is trickier to do automatically, especially for sequencing techs that don't always have the same number of bases.

**Comment by gregcaporaso** [comment]
> Making `trunc-len` optional is trickier to do automatically, especially for sequencing techs that don't always have the same number of bases.

I was thinking that it would default to not trimming.

**Comment by benjjneb** [comment]
The dada2 code currently requires all input sequences to be the same length, although if all goes well that requirement will be removed in our next release.

**Comment by gregcaporaso** [comment]
OK, we can hold off on that until then.

**Comment by ebolyen** [comment]
FYI: `trim-left` is already set to default to `0` (in the 2017.2 release).

**Comment by benjjneb** [comment]
I pushed variable-length support to the main devel-branch of dada2 today (cddce98a98894e4a621f6767e61fe9aaed638e06) so this feature will definitely be in the upcoming 1.4 release.

Another consequence, dada2 now works for ITS data, since trimming to a fixed length is no longer required.

**Comment by ebolyen** [comment]
This was resolved in #66.
