### ISSUE TITLE
Verify that sample-ids with underscore characters are preserved

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-dada2#46]
This came up on the [forum](https://forum.qiime2.org/t/how-to-build-sample-metadata-tsv-in-demux-paired-end-data/374).

I need to verify this behavior, however I believe it's probably the result of this plugin.

**Comment by benjjneb** [comment]
This probably derives from the way the file-names are parsed by the python script: https://github.com/qiime2/q2-dada2/blob/master/q2_dada2/_denoise.py#L72

Right now it looks like files are assumed to be named in `SAMPLENAME_XXX.fastq.gz` format.

**Comment by ebolyen** [comment]
That looks like it! It should probably be using `rsplit` with a cut-off.

**Comment by ebolyen** [comment]
Looks like we ran into this again. I'll try and prioritize this for the May release.
