### ISSUE TITLE
resolve potential bug related to missing filtered samples

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-dada2#49]
edit by @ebolyen for future searching in case we see this again:
```
Error in open.connection(con, "rb") : cannot open the connection
Calls: derepFastq ... FastqStreamer -> FastqStreamer -> open -> open.connection
In addition: Warning message:
In open.connection(con, "rb") :
  cannot open file '/var/folders/qr/vd5b6lqx18z8zzhc612cwk9r0000gn/T/tmphkndm05o/filt_f/16_S11_L001_R1_001.fastq.gz': No such file or directory
Execution halted
```
/edit

This came up a couple of times on the forum and is actively being debugged by @ebolyen and @benjjneb. See [this topic](https://forum.qiime2.org/t/dada2-no-such-file-or-directory-and-error-in-open-connection-message/412/12) for details. Creating a placeholder issue to track progress.

**Comment by ebolyen** [comment]
Can't seem to reproduce. Closing this issue.
