### ISSUE TITLE
Installation documentation issues on mac osx

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-dada2#5]
I am working from the `q2-dada2` plugin install instructions provided [here](https://github.com/gregcaporaso/q2-dada2), and installing on mac osx 10.11.6. A couple issues came up during installation, and I am posting these as a work-around.

1) The most recent version of `R` appears to be incompatible with the dada2 dependency `biocgenerics`, so version `r=3.2.2` needs to be specified in the install. Additionally, a number of other `R` packages that are dependencies for `biocgenerics` also need to be installed using the `R` channel (they are missing in the bioconda channel apparently, so don't install when installing bioconductor-dada2). To solve this, I modified the environment creation command to:
`conda create -n q2-dada2 -c r r=3.2.2 python=3.5 r-bitops r-latticeextra r-data.table r-foreach r-ggplot2 r-gridextra r-rcpp`

2) `matplotlib` error. When I run `qiime --help`:
`RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ`

According to [working with matplotlib in virtual environments](http://matplotlib.org/faq/virtualenv_faq.html), this should not be an issue with conda. As `matplotlib` is installed with pip above, this appears to be the issue, so I uninstalled, then reinstalled with conda to make this work:
`pip uninstall matplotlib`
`conda install matplotlib`

Following these fixes, I can confirm that `qiime2-dev` and `q2-dada2` are properly installed:
`qiime dada2 --help`

**Comment by gregcaporaso** [comment]
Thanks @nbokulich, this will be really helpful as we work on documentation of the whole pipeline next week. Glad it's working for you now!

**Comment by nbokulich** [comment]
Also, the plugin [tutorial](https://github.com/gregcaporaso/q2-dada2) does not include install instructions for [q2-emperor](https://github.com/qiime2/q2-emperor/), and should be added to the documentation.

Apparently, the current q2-emperor release (following the [qiime2 installation](https://github.com/qiime2/qiime2/wiki/Installing-and-using-QIIME-2) and running in a separate conda env) is unable to read the ``bray-curtis PC`` file produced by these instructions, producing the following error:
``KeyError: "There is no item named 'bray-curtis-pc/VERSION' in the archive``

I assume that is because there is a dev version that must be installed to work with the current ``q2-dada2`` tutorial, and the install instructions should be provided here for q2-emperor-dev. Do you know, @gregcaporaso ? If this is not the case, perhaps I should report a separate issue to q2-emperor?

**Comment by gregcaporaso** [comment]
Yep, you'll need to install the development version of `q2-emperor` for it to work. The note on this issue will serve as a reminder.

**Comment by nbokulich** [comment]
In case it's any help, here's the full list of install commands I used to get dada2 working from start to finish, including emperor (with the exception of [issue-6](https://github.com/benjjneb/q2-dada2/issues/6)):

``conda create -n q2-dada2 -c r r=3.2.2 python=3.5 r-bitops r-latticeextra r-data.table r-foreach r-ggplot2 r-gridextra r-rcpp``
``source activate q2-dada2``
``conda install -c bioconda bioconductor-dada2``
``conda install matplotlib``
``pip install https://github.com/qiime2/qiime2/archive/master.zip https://github.com/qiime2/q2cli/archive/master.zip https://github.com/qiime2/q2-types/archive/master.zip https://github.com/qiime2/q2-feature-table/archive/master.zip https://github.com/gregcaporaso/q2-dada2/archive/master.zip``
``conda install -c qiime2 -c biocore q2-emperor``
``qiime dada2 --help``

**Comment by benjjneb** [comment]
I also installed the current version on MacOSX. I had to add a couple more lines to @nbokulich recipe, to add the R channel and to also install scipy and numpy:

```
conda config --add channels r
conda create -n q2-dada2 -c r r=3.2.2 python=3.5 r-bitops r-latticeextra r-data.table r-foreach r-ggplot2 r-gridextra r-rcpp
source activate q2-dada2
conda install -c bioconda bioconductor-dada2
conda install -c anaconda numpy scipy matplotlib
pip install https://github.com/qiime2/qiime2/archive/master.zip https://github.com/qiime2/q2cli/archive/master.zip https://github.com/qiime2/q2-types/archive/master.zip https://github.com/qiime2/q2-feature-table/archive/master.zip https://github.com/gregcaporaso/q2-dada2/archive/master.zip
conda install -c qiime2 -c biocore q2-emperor
qiime dada2 --help
```

**Comment by jairideout** [comment]
Closing because this is pretty old and a lot's changed wrt packages and installation.
