### ISSUE TITLE
Add chimera filtering options

### ISSUE THREAD

**Issue by benjjneb** [qiime2/q2-dada2#50]
In my opinion the options related to chimera removal are important to expose to users of the plugin. This is especially true because dada2 implements two kinds of chimera removal (pooled and consensus), and as of our next 1.4 release we will be officially recommending consensus removal for large datasets (default is pooled).

**Comment by gregcaporaso** [comment]
Is this something that could happen with the current release, or does it depend on the 1.4 release of DADA2?

**Comment by benjjneb** [comment]
Can be done now, but multithreading will only work on pooled chimera removal until 1.4.

I'll make a branch with an updated R script.

**Comment by benjjneb** [comment]
Added in 2017.4
