### ISSUE TITLE
Add truncLen requirements to the denoise-paired help text

### ISSUE THREAD

**Issue by benjjneb** [qiime2/q2-dada2#52]
For the F/R reads to be successfully merged, `trunc-len-f` + `trunc-len-r` must be greater than the length of the amplicon + 20 nucleotides (the 20 nts is the length of the overlap).

This requirement should be reflected in the documentation for `denoise-paired`.

**Comment by maxvonhippel** [comment]
Note that in the code these appear as `truncLenF` and `truncLenR`.

Also, I'm working on this now.

**Comment by jairideout** [comment]
Fixed in #63
