### ISSUE TITLE
plot-qualities produces empty data directory

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-dada2#6]
I am following the tutorial instructions provided [here](https://github.com/gregcaporaso/q2-dada2).

the `plot-qualities` command runs without error, but the `data/` directory in the output is empty. Consequently, running `qiime tools view quality-plots.qzv` produces an empty page. I have tested this with both the test files provided and with real data files, so suspect this is an issue with the code rather than the files.

However, the subsequent commands in the tutorial are functional, e.g., the following produces the expected output:
`qiime dada2 denoise --i-demultiplexed-seqs fmt-tutorial-per-sample-fastq-1p.qza --o-table fmt-tutorial-table.qza --p-trim-left 10 --p-trunc-len 130 --o-representative-sequences fmt-tutorial-rep-seqs.qza`

Hence, I believe that this issue is isolated to the `plot-qualities` command.

**Comment by benjjneb** [comment]
Closing since this function is being deprecated for most users in favor of the new interactive quality plot.
