### ISSUE TITLE
A workaround for q2-dada2 and a local R installation with dada2

### ISSUE THREAD

**Issue by ebolyen** [qiime2/q2-dada2#68]
This has come up before and we've finally figured out a "workaround". This probably needs to be solved in a deeper way, but to record what works:

R loads it's libraries from `.libPaths()`. On mac OS X installations with an R Studio installation, the R Studio path ends up in `.libPaths()` as the highest priority, so if a user has dada2 installed locally, it will use that which is linked against a different R binary, so you'll get a segfault (if you're lucky).

What you can do is create an `.Rprofile` file and place:
```
.libPaths(.libPaths()[2])
```

This is gross, but it's a start for a better solution.

**Comment by ebolyen** [comment]
x-ref: was used to solve this [forum post](https://forum.qiime2.org/t/exit-code-11-from-dada2/1206).

**Comment by gtsiamis** [comment]
I am getting the same -11 error.

I created an .Rprofile file in my home directory (please see screenshot of the file) but I am still having the same issue:
Plugin error from dada2:

  An error was encountered while running DADA2 in R (return code -11),
  please inspect stdout and stderr to learn more.
 
My configuration is OS X 10.10.5 and I am using Rstudio.

Looking forward to your advice
![screen shot 2017-10-02 at 20 04 27](https://user-images.githubusercontent.com/2630188/31089478-f7b222dc-a7ac-11e7-95b8-2a9815e07383.png)

.

Kind regards
George

**Comment by ebolyen** [comment]
Hey @gtsiamis, that looks right, but your file name needs to start with a dot (`.`) So it should be `.Rprofile` not `Rprofile`.

**Comment by gtsiamis** [comment]
When I tried to upload the file .Rprofile in my previous comment I got the
message that it cannot upload invisible files (with the dot in the
begining) so I remove the dot for this reason. In the directory the file is
invisible (with the dot)

This is how my .Rprofile looks like in the home directory

[image: Inline images 1]


Any suggestions

George


George Tsiamis, Ph.D.
Assistant Professor in Environmental Microbiology
Department of Environmental and Natural Resources Management
University of Patras
2 Seferi str., Agrinio
30100, Greece
e-mail: gtsiamis@ <gtsiamis@cc.uoi.gr>upatras, gtsiamis1@gmail.com
tel. +302641074149, fax. +302641074171
*Assistant Specialty Chief Editor Systems Microbiology*

**Comment by ebolyen** [comment]
Hey @gtsiamis, I think this is starting to turn into more of a support discussion, which is best handled on our [QIIME 2 forum](https://forum.qiime2.org).
We try and keep GitHub issues related strictly to development efforts and use-cases. Please feel free to create a topic on the forum however!

**Comment by gtsiamis** [comment]
Thanks Evan.

I posted my inquiry to the qiime2 forum.

Thanks
George


George Tsiamis, Ph.D.
Assistant Professor in Environmental Microbiology
Department of Environmental and Natural Resources Management
University of Patras
2 Seferi str., Agrinio
30100, Greece
e-mail: gtsiamis@ <gtsiamis@cc.uoi.gr>upatras, gtsiamis1@gmail.com
tel. +302641074149, fax. +302641074171
*Assistant Specialty Chief Editor Systems Microbiology*

**Comment by ebolyen** [comment]
I think I have a new way to fix this, but we'd need to test it to be sure.

There are [a couple of environment variables](https://stat.ethz.ch/R-manual/R-devel/library/base/html/EnvVar.html) that impact `libPaths`:
```
R_LIBS
R_LIBS_SITE
R_LIBS_USER
```

If these do what they look like they do, it would be possible to create pre-activation and post-activation scripts in the conda package which would set the variables to look exclusively in the conda environment instead of adding R Studio's user-based R and packages.

**Comment by ebolyen** [comment]
More progress:

In `~/.conda/envs/<whatever>/lib/R/etc/Renviron` there is a line that will look something like:
```
R_LIBS_USER=${R_LIBS_USER-'~/R/x86_64-pc-linux-gnu-library/3.4'}
```
Commenting it out prevents RStudio's packages from interferring with the conda environment.

Some permanent options to fix this:

1. Create a bunch of patch files for different OS configurations (this sounds annoying and probably belongs in R-Base if anywhere), conda has an entire directive for this, so it's not an odd thing to do.
2. Just set `R_LIBS_USER` to a file/directory that doesn't exist `/DONT/LOOK/HERE` or `/dev/null` 

Option 2 is easy, but kind of gross. Option 1 is harder, but probably the "right way" to go about this.

**Comment by ebolyen** [comment]
This command will edit the `Renviron` in your currently active environment.
It's not pretty, but it's trying to keep you from nuking your system R on accident.
```
_renv=$(which qiime | sed 's/bin\/qiime/lib\/R\/etc\/Renviron/'); [[ -f $_renv ]] && sed -i '/R_LIBS_USER/d' $_renv
```
