### ISSUE TITLE
expose minimum-length parameter?

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-dada2#72]
Question [came up on the forum](https://forum.qiime2.org/t/questions-on-dada2-implementation/709/8) about whether we should expose the minimum-length parameter in q2-dada2. Current behavior is minimum-length=20.

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/its-fungi-dada2-question-not-all-sequences-were-the-same-length/7831/3?u=nicholas_bokulich)

**Comment by benjjneb** [comment]
Can sequences be filtered out if they are below a minimum length by `filter-features`?

If so, I think it is preferable to leave this functionality to that plugin rather than adding another parameter here.

**Comment by ebolyen** [comment]
We don't have functionality for that, but it is a good idea. I think it would go in `filter-seqs` and then you could treat that as a set of ids for `filter-features`.

**Comment by benjjneb** [comment]
OK, I am changing this to wont-fix here then, as I think the best solution would be to put this functionality in `filter-seqs` or `filter-features`. I'll leave it open though until an issue is created at whatever the right location would be for that plugin.

**Comment by thermokarst** [comment]
xref: https://github.com/qiime2/q2-feature-table/issues/151
