### ISSUE TITLE
adding 454/ion torrent support

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-dada2#76]
I think this is just a matter of exposing the parameters described [here](https://benjjneb.github.io/dada2/faq.html#can-i-use-dada2-with-my-454-or-ion-torrent-data). I can take this one (either for 2017.10 or 2017.11), and will do some research when I work on it to figure out if it makes sense as part of an existing method or a new one or two.

**Comment by benjjneb** [comment]
On the dada2 side, we are updating our recommendations for IT/454. They now both should use `HOMOPOLYMER_GAP_PENALTY=-1` and `BAND_SIZE=32`.

I think that a new command to handle both IT and 454 makes sense, something like `denoise-pyro`.

For 454, it would be recommended to expose the `maxLen` filtering parameter, as long 454 sequences were bad quality even if it didn't show up in quality scores. That doesn't matter for IT as they are all the same length.

**Comment by thermokarst** [comment]
This recently [came up on the forum](https://forum.qiime2.org/t/is-dada2-ok-for-ion-torrent-and-454-sequencing-now/3382?u=thermokarst).
