### ISSUE TITLE
Upgrading to 2017.12 breaks `q2-dada2`/`dada2` 

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2-dada2#84]
Under `qiime2=2017.12` `q2-dada2` does not work (tested on multiple `conda` environments, both local (macOS) and remote (Ubuntu 16.04 on EC2). It appears to be missing a `GenomeInfoDbData` requirement and will fail to load. 

Here's an R terminal attempt to load `dada2` independent of `qiime2` to show the error (same error spit into terminal through `q2-dada2`):
![image](https://user-images.githubusercontent.com/2638727/34853485-d361b3d0-f6e8-11e7-8ad4-0390e5d5bfdd.png)

Unsure if it's something in the `q2-dada2` installation that is failing, or if a dependency of `dada2` itself has become unreachable? Only relevant issue I could find was [this](https://forum.qiime2.org/t/2017-12-installation-issues-download-stalls/2422) on the forum.

---
edit: this remains as an issue even after `conda env update --file 2017.12` from [here](https://forum.qiime2.org/t/new-conda-installation-scheme/2528?u=jakereps)

**Comment by thermokarst** [comment]
Thanks @jakereps ! I just tried to reproduce in a fresh macos install, using conda 4.4 and a brand new environment and was not able to raise this same error. What are the contents of the env (`conda list`)? What version of conda are you using? Do you see the same thing when installing a fresh env? We will get to the bottom of this!

**Comment by jakereps** [comment]
Currently upgrading (2017.9->2017.12) one more local (macOS) env to see if it works, but the EC2 is:

```powershell
(biota) jorden@ip-867-53-0-9:~$ conda --version
conda 4.4.7
(biota) jorden@ip-867-53-0-9:~$ conda list
<Attached as gist>[1]
```

[1] https://gist.github.com/jakereps/d24ff42df8a0f137b89c412a872ef9ac

**Comment by jakereps** [comment]
After updating (macOS 2017.9 -> 2017.12) it breaks `dada2` (this is on the macOS 12.13.2 mentioned above, which worked pre-2017.12 update)

```powershell
(biota) [16:55]:~$ R -e "library('dada2');"

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin14.5.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library('dada2');
Loading required package: Rcpp
Error: package or namespace load failed for ‘dada2’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’
Execution halted
(biota) [16:55]:~$ 
```

**Comment by jakereps** [comment]
Update: It works as expected only on _brand new_ environments. All (Ubuntu/macOS) environments it broke under were existing environments being updated.


```powershell
[17:36]:~$ conda env create -n qiime2-2017.12 --file qiime2-2017.12-py35-osx-conda.yml
...yada yada...
[17:42]:~$ act qiime2-2017.12
(qiime2-2017.12) [17:43]:~$ R -e "require('dada2');"

R version 3.4.1 (2017-06-30) -- "Single Candle"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin14.5.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require('dada2');
Loading required package: dada2
Loading required package: Rcpp
> 
> 

(qiime2-2017.12) [17:43]:~$ 
```

**Comment by thermokarst** [comment]
Thanks @jakereps! I don't have a great answer for you, but, we have observed a lot of churn over on the conda issue tracker related to the new 4.4 release --- I wouldn't be surprised if this was somehow related. Stay tuned!

**Comment by ebolyen** [comment]
I think I know what might be happening here. There is probably a dependency once-removed that added GenomeInfoDBData to a newer version (pretty sure it was just GenomeInfoDB). On bioconda, the bioconductor packages don't seem to have a way to ensure they are installed alongside the other release in their respective train-release, so conda figures out update plan which keeps some of your old dependencies, but upgrades others. These are incompatible and lead to the missing dep above.

What doesn't really make sense is why the environment file isn't updating *everything* since I can see bioconductor-genomeinfodbdata listed in there. What does `conda list` on a broken environment show?

**Comment by jakereps** [comment]
@ebolyen I did notice that running it on a _newer_ environment the installation list was relatively short, so it does seem to be piecewise updates. [The first](https://github.com/qiime2/q2-dada2/issues/84#issuecomment-357109947) gist is of a broken env.

**Comment by jakereps** [comment]
@thermokarst The macOS update error is in `4.3` [here](https://gist.github.com/jakereps/f728a04ed769ebef33503c0a2cb40f1e#file-gistfile1-txt-L99), so it seems to occur in both `4.3` and `4.4`. `4.3.25` failed to upgrade to `2017.12` entirely because it couldn't find `mkl` I guess?

**Comment by jakereps** [comment]
Update: Resolved by doing `conda install --file ...txt` within the environment (realized those are still generated in qiime2/environment-files, just not published on the docs site) instead of doing the yml update. 

Leaving the issue open as the new recommended update [on the forum is using the yml file](https://forum.qiime2.org/t/new-conda-installation-scheme/2528), which is what caused this issue.
