### ISSUE TITLE
Turning chimera checking off breaks the plugin

### ISSUE THREAD

**Issue by benjjneb** [qiime2/q2-dada2#88]
Need to add assignment `seqtab.nochim <- seqtab` to the R scripts when the chimera method is "none".

Should also probably add a test checking that the plugin runs w/ the different chimera modes.

**Comment by thermokarst** [comment]
This recently [came up on the forum](https://forum.qiime2.org/t/dada2-error-running-without-chimera-checking/2988?u=thermokarst).
