### ISSUE TITLE
Add parallel functionality

### ISSUE THREAD

**Issue by johnchase** [qiime2/q2-dada2#9]
It would  be a great addition to be able to run q2-dada in parallel.

**Comment by benjjneb** [comment]
Right now the q2 plugin is using the 1.0.3 release of dada2, not the development branch, so multithreading isn't available.

The next dada2 release (1.2) is next month, and will have multithreading. It probably makes the most sense for stability reasons to migrate to the next release before adding multithreading to the plugin.

There are also some modifications to the plugin workflow that would speed things up a lot for larger datasets (basically estimating error rates from a subset of the data).

**Comment by benjjneb** [comment]
This depends on #13 (installation of up-to-date dada2 release).

**Comment by benjjneb** [comment]
Added in 685ddae848e46090aea61809373e7c86757f0676 and b66432da308a924a26f315a517c934b4a335af2f

Assumes dada2 1.2+
