### ISSUE TITLE
Error in isBimeraDenovoTable(unqs[[i]], ..., verbose = verbose) :    Input must be a valid sequence table.

### ISSUE THREAD

**Issue by bassio** [qiime2/q2-dada2#90]
Hello,
I got the error below at the step of chimera detection.
I wonder if this is that there were no sequences left for chimera detection at the end of that stage.
Running qiime 2 Feb 2018 version.
Let me know if you need any further info

See below for error report:

Running external command line application(s). This may print messages to stdout and/or stderr.
The command(s) being run are below. These commands cannot be manually re-run as they will depend on temporary files that no longer exist.

Command: run_dada_paired.R /tmp/tmps4hlcnk7/forward /tmp/tmps4hlcnk7/reverse /tmp/tmps4hlcnk7/output.tsv.biom /tmp/tmps4hlcnk7/filt_f /tmp/tmps4hlcnk7/filt_r 260 260 0 0 2.0 2 consensus 1.0 1 1000000

R version 3.4.1 (2017-06-30) 
Loading required package: Rcpp
DADA2 R package version: 1.6.0 
1) Filtering ...
2) Learning Error Rates
2a) Forward Reads
Initializing error rates to maximum possible estimate.
Sample 1 - 2656 reads in 1987 unique sequences.
Sample 2 - 6060 reads in 2150 unique sequences.
Sample 3 - 11141 reads in 3185 unique sequences.
   selfConsist step 2 
   selfConsist step 3 
   selfConsist step 4 
   selfConsist step 5 
Convergence after  5  rounds.
2b) Reverse Reads
Initializing error rates to maximum possible estimate.
Sample 1 - 2656 reads in 1987 unique sequences.
Sample 2 - 6060 reads in 2150 unique sequences.
Sample 3 - 11141 reads in 3185 unique sequences.
   selfConsist step 2 
   selfConsist step 3 
   selfConsist step 4 
   selfConsist step 5 
Convergence after  5  rounds.

3) Denoise remaining samples 
4) Remove chimeras (method = consensus)
Error in isBimeraDenovoTable(unqs[[i]], ..., verbose = verbose) : 
  Input must be a valid sequence table.
Calls: removeBimeraDenovo -> isBimeraDenovoTable
In addition: Warning message:
In is.na(colnames(unqs[[i]])) :
  is.na() applied to non-(list or vector) of type 'NULL'
Execution halted

**Comment by thermokarst** [comment]
Hi @bassio - can you please post this question to the QIIME 2 Forum, at https://forum.qiime2.org? That is where we provide user support for QIIME 2. Thanks for your understanding!
