### ISSUE TITLE
Improve summary for merging paired reads 

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-dada2#98]
This suggestion came from the forum: https://forum.qiime2.org/t/sequence-length-report-after-dada2-denoise-pair/3908/9?u=antgonza

The new summary could have:
- the input length of the fastq/fasta
- the overlap between reads after denoising
- the final length of the final sequences

**Comment by nbokulich** [comment]
This may be a partial overlap of [this issue](https://github.com/qiime2/q2-demux/issues/71)

**Comment by mdehollander** [comment]
Is there already a way to get a summary of the length distribution of the merged reads?

**Comment by thermokarst** [comment]
You can get a length distribution summary for any `FeatureData[Sequence]` artifact using [`feature-table tabulate-seqs`](https://docs.qiime2.org/2019.10/plugins/available/feature-table/tabulate-seqs/).

**Comment by mdehollander** [comment]
Thanks, that works indeed.
