### ISSUE TITLE
Add more DADA2 parameters to the wrapper

### ISSUE THREAD

**Issue by apcamargo** [qiime2/q2-dada2#99]
For some types of analysis it is desired to tweak some DADA2 parameters that are not available in the QIIME 2 wrapper, such as BAND_SIZE, OMEGA_A and OMEGA_C (the latter is only available in version 1.8).

I recently did a analysis with ITS2 data, which required me to change the BAND_SIZE. Because of that, I had to run the denoising step in R and then import the results into QIIME 2.

Maybe we could start a discussion of which parameters could be added to q2-dada2.

**Comment by ebolyen** [comment]
#51 may also be relevant to the conversation. It seems like DADA2 has a bunch of functionality which would be great to expose in a more granular way (with all of the new parameters). As well as having some easy pipelines which do most of the work for simple situations.

**Comment by benjjneb** [comment]
Happy to take suggestions. We will be doing an update once dada2 1.8 is released on Bioconda (July maybe) letting us transition to the new version for the plugin.

`OMEGA_A`, `BAND_SIZE` and `pool` seem to me like clear candidates to expose.

**Comment by benjjneb** [comment]
At this point in time I'm not planning on exposing `OMEGA_A` or `OMEGA_C` in the plugin. I am planning on adding a `pool` parameter with the dada2v1.10 update.
